services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 443:443
    volumes:
      - nginx_certs:/etc/nginx/ssl/:ro
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - 9000:9000
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress_user
      - MARIADB_PASSWORD=wordpress_password
    networks:
      - inception
    

networks:
  inception:
    name: inception_network
    driver: bridge

volumes:
  nginx_certs:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/certs/
      o: bind
