services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - nginx_certs:/etc/nginx/ssl/:ro
      - wordpress_data:/var/www
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    build: ./wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www
    secrets:
      - wp_admin_password
      - wp_admin_user
      - wp_user_password
      - wp_user
      - db_password
      - db_password
    networks:
      - inception
    depends_on:
      - mariadb
    
  mariadb:
    build: ./mariadb
    image: mariadb
    restart: always
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    networks:
      - inception
  
  ftp:
    build: ./ftp
    image: ftp
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file: .env
    secrets:
      - ftp_password
    volumes:
      - wordpress_data:/home/ftpuser/
    networks:
      - inception
    depends_on:
      - wordpress

  redis:
    build: ./redis
    image: redis
    container_name: redis
    restart: always
    networks:
      - inception

  adminer:
    build: ./adminer
    image: adminer
    container_name: adminer
    restart: always
    networks:
      - inception
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    depends_on:
      - mariadb  

  vitrine:
    build: ./vitrine
    image: vitrine
    container_name: vitrine
    restart: always
    volumes:
      - vitrine_data:/var/www/
    networks:
      - inception
    depends_on:
      - wordpress

  code:
    build: ./code
    image: code
    container_name: code
    restart: always
    volumes:
      - wordpress_data:/var/www/wordpress
      - vitrine_data:/var/www/vitrine
    secrets:
      - code_password
    networks:
      - inception

networks:
  inception:
    name: inception_network
    driver: bridge

volumes:
  nginx_certs:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/certs/
      o: bind

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb/
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress/
      o: bind

  vitrine_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/vitrine/
      o: bind

secrets:
  db_root_password:
    file: ./mariadb/secrets/db_root_password

  db_password:
    file: ./secrets/db_password

  wp_admin_password:
    file: ./wordpress/secrets/wp_admin_password

  wp_admin_user:
    file: ./wordpress/secrets/wp_admin_user

  wp_user_password:
    file: ./wordpress/secrets/wp_user_password

  wp_user:
    file: ./wordpress/secrets/wp_user

  ftp_password:
    file: ./secrets/ftp_password

  code_password:
    file: ./code/secrets/code_password