services:
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      # - 443:443
      - 4443:4443
    volumes:
      - nginx_certs:/etc/nginx/ssl/:ro
      - wordpress_data:/var/www
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    build: ./wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www
    secrets:
      - wp_admin_password
      - db_password
    networks:
      - inception
    depends_on:
      - mariadb
    
  mariadb:
    build: ./mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    ports:
      - 3306:3306
    networks:
      - inception
  
  ftp:
    build: ./ftp
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file: .env
    secrets:
      - ftp_password
    volumes:
      - wordpress_data:/home/ftpuser/
    networks:
      - inception
    depends_on:
      - wordpress

  adminer:
    build: ./adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - inception
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    depends_on:
      - mariadb  

networks:
  inception:
    name: inception_network
    driver: bridge

volumes:
  nginx_certs:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/certs/
      o: bind

  mariadb_data:
  wordpress_data:

secrets:
  db_root_password:
    file: ./mariadb/secrets/db_root_password

  db_password:
    file: ./secrets/db_password

  wp_admin_password:
    file: ./wordpress/secrets/wp_admin_password

  ftp_password:
    file: ./secrets/ftp_password