services:
  nginx:
    build: ./nginx
    container_name: nginx_inception
    restart: always
    ports:
      - 443:443
    volumes:
      - nginx_certs:/etc/nginx/ssl/:ro
    networks:
      - inception
    depends_on:
      - wordpress

  wordpress:
    build: ./wordpress
    container_name: wordpress_inception
    restart: always
    ports:
      - 9000:9000
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress_user
      - MARIADB_PASSWORD=wordpress_password
      - MARIADB_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=wordpress_password
    networks:
      - inception
    depends_on:
      - mariadb
    
  mariadb:
    build: ./mariadb
    container_name: mariadb_inception
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress_user
      - MARIADB_PASSWORD=wordpress_password
      - MARIADB_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=wordpress_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - inception
  
  adminer:
    build: ./adminer
    container_name: adminer_inception
    restart: always
    ports:
      - 8080:8080
    networks:
      - inception
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb_inception
    depends_on:
      - mariadb
    

networks:
  inception:
    name: inception_network
    driver: bridge

volumes:
  nginx_certs:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/certs/
      o: bind

  mariadb_data: