services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    networks:
      - inception
    

networks:
  inception:
    name: inception_network
    driver: bridge
