services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - nginx_certs:/etc/nginx/certs:ro
    networks:
      - inception

  # wordpress:
  #   build:
  #     context: ./wordpress
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:80

  #   networks:
  #     - inception
    

networks:
  inception:
    name: inception_network
    driver: bridge

volumes:
  nginx_certs:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/certs/
      o: bind
